# Generated by Django 3.1.2 on 2020-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20201022_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제 날짜'),
        ),
    ]
